 Creation of Array

In [16]:
#Exp no. : 5

In [7]:
#Aim : Creation of Array (1D,2D and Multidimennsional array) using numpy

In [8]:
#Name: Ayush Nagdive
#Roll no:42
#Sec:B
#Subject:ET1

In [9]:
import numpy as np

In [10]:
arr1=np.array([10,20,30,40,50])

In [11]:
arr1

array([10, 20, 30, 40, 50])

In [12]:
arr2=np.array([[10,20,30,40,50],[60,70,80,90,100]])

In [13]:
arr2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [14]:
arr3=np.array([[10,20,30,40,50],[60,70,80,90,100],[15,25,35,45,55]])

In [15]:
arr3

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [ 15,  25,  35,  45,  55]])